name: Reincarnation
version: '${version}'
api-version: '1.17'
description: Reincarnation's core system.
main: net.azisaba.rc.Reincarnation
depend:
  - JunkGames
commands:
  rc:
    description: Supports reincarnation processing.
    usage: /rc <skill> <args…>